### ISSUE TITLE
Re-enable TSAN job, and add support for suppression files.

### ISSUE THREAD

**Issue by thomas-moulard** [ros-tooling/system_metrics_collector#10]
See [TSAN documentation here](https://github.com/google/sanitizers/wiki/ThreadSanitizerSuppressions).

This would help us getting back the TSAN job back to green and focus more on race conditions inside this package.

**Comment by emersonknapp** [comment]
@thomas-moulard is there a TSAN job for this package? is this ticket still relevant?

**Comment by thomas-moulard** [comment]
@emersonknapp I'd like us to continue making *SAN jobs a priority, so I rephrased the issue.

**Comment by emersonknapp** [comment]
Closing as stale, reopen later if wanted
