### ISSUE TITLE
Allow topic statistics to subscribe to multiple topics

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-tooling/system_metrics_collector#118]
**Originally in https://github.com/ros-tooling/system_metrics_collector/pull/112#discussion_r398293858**

Right now the SubscriberTopicStatisticsNode class subscribes to only one topic for statistics collection. We want to modify it to be able to subscribe and report statistics on multiple  topics.

## Description

Change the topic parameter and subscriptions in SubscriberTopicStatisticsNode to handle multiple topics and subscriptions.

## Test Plan
* New unit tests
* Modify e2e test to test multiple topics

## Documentation Plan

* Docstrings and README update

## Release Plan

* Check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Implementation notes

* Mind multiple times the same topic (so maybe use an unordered_map)
* Mind 0 topics passed to the param

## Resources

Class to modify: [SubscriberTopicStatistics](https://github.com/ros-tooling/system_metrics_collector/blob/master/system_metrics_collector/src/topic_statistics_collector/subscriber_topic_statistics.hpp)

**Comment by prajakta-gokhale** [comment]
Reviewed at Sprint 18 review. Needs a demo before closing.

**Comment by snehaldb90** [comment]
**CLI Demo:**

**Terminal 1**: ros2 topic pub /my_topic1 std_msgs/String "data: Hello World1"
**Output**: publisher: beginning loop
publishing #1: std_msgs.msg.String(data='Hello World1')
publishing #2: std_msgs.msg.String(data='Hello World1')

**Terminal 2**: ros2 topic pub /my_topic2 std_msgs/String "data: Hello World2"
**Output**: publisher: beginning loop
publishing #1: std_msgs.msg.String(data='Hello World2')
publishing #2: std_msgs.msg.String(data='Hello World2')

**Terminal 3**: ros2 run system_metrics_collector topic_statistics_node

**Terminal 4**: ros2 topic echo /system_metrics
**Output**: measurement_source_name: topic_statistics_collector
metrics_source: message_age
unit: ms
window_start:
  sec: 1591912828
  nanosec: 437197014
window_stop:
  sec: 1591912828
  nanosec: 437199284
statistics:
- data_type: 1
  data: .nan
- data_type: 3
  data: .nan
- data_type: 2
  data: .nan
- data_type: 5
  data: 0.0
- data_type: 4
  data: .nan
--
measurement_source_name: topic_statistics_collector
metrics_source: message_period
unit: ms
window_start:
  sec: 1591912828
  nanosec: 437197014
window_stop:
  sec: 1591912828
  nanosec: 437238975
statistics:
- data_type: 1
  data: 499.5
- data_type: 3
  data: 676.0
- data_type: 2
  data: 323.0
- data_type: 5
  data: 2.0
- data_type: 4
  data: 176.5
--

**Terminal 6:** : ros2 topic info -v /my_topic1
Type: std_msgs/msg/String

Publisher count: 0

Subscription count: 1

Node name: topic_statistics_collector
Node namespace: /
Topic type: std_msgs/msg/String
Endpoint type: SUBSCRIPTION
GID: 01.0f.e9.88.3c.2c.00.00.01.00.00.00.00.00.1d.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RMW_QOS_POLICY_RELIABILITY_RELIABLE
  Durability: RMW_QOS_POLICY_DURABILITY_VOLATILE
  Lifespan: 2147483651294967295 nanoseconds
  Deadline: 2147483651294967295 nanoseconds
  Liveliness: RMW_QOS_POLICY_LIVELINESS_AUTOMATIC
  Liveliness lease duration: 2147483651294967295 nanoseconds

**Terminal 7:**: ros2 topic info -v /my_topic2
Type: std_msgs/msg/String

Publisher count: 0

Subscription count: 1

Node name: topic_statistics_collector
Node namespace: /
Topic type: std_msgs/msg/String
Endpoint type: SUBSCRIPTION
GID: 01.0f.e9.88.3c.2c.00.00.01.00.00.00.00.00.1e.04.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RMW_QOS_POLICY_RELIABILITY_RELIABLE
  Durability: RMW_QOS_POLICY_DURABILITY_VOLATILE
  Lifespan: 2147483651294967295 nanoseconds
  Deadline: 2147483651294967295 nanoseconds
  Liveliness: RMW_QOS_POLICY_LIVELINESS_AUTOMATIC
  Liveliness lease duration: 2147483651294967295 nanoseconds

**Comment by snehaldb90** [comment]
New issue created: https://github.com/ros-tooling/system_metrics_collector/issues/148
To specify the subscribed topic name in topic statistics.
