### ISSUE TITLE
INVALID_PUBLISH_WINDOW is defined as 0 ms

### ISSUE THREAD

**Issue by mm318** [ros-tooling/system_metrics_collector#20]
Using `std::chrono::milliseconds(0)` as a sentinel value for an invalid publishing period is a bad choice.

**Comment by dabonnie** [comment]
Can you please elaborate why? :-)

**Comment by mm318** [comment]
I'll close this issue as I don't feel strongly about it.

There was concern about 0 being a commonly used value, but it has been wrapped in a `chrono::millisecond`. Then there was concern about negative durations causing exceptions to be [thrown](https://github.com/ros-tooling/system_metrics_collector/commit/2446d4fc6754d73926d6c1096f2594e052610114#r36230509). Neither of which seem to be that immediately concerning.
