### ISSUE TITLE
Collector add measurement window

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/system_metrics_collector#27]
Provide the start time of the collection window of the currently active measurement set.

I think we should add this in the collector: I'll file an issue as a separate PR.

_Originally posted by @dabonnie in https://github.com/ros-tooling/system_metrics_collector/pull/16/review_comment/create_

**Comment by dabonnie** [comment]
After some investigation I'm not sure if this is a good approach given that, in order to use system and simulated time, the node must provide the time via the now() call. Given that Collector is not a node nor extends it, the logic in PeriodicMeasurementNode seems fine unless we want to embed the clock in the collector.

**Comment by emersonknapp** [comment]
Closing as no longer relevant
