### ISSUE TITLE
View System Metrics Data

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/system_metrics_collector#47]
## Description

Provide a simple standalone utility to view logged system metric data. The problem can be split into the following:

* [ ] Log the data into a parseable format for a display tool
* [ ] Parse the logged data
* [ ] Plot the data

## Test Plan

* Manual testing
* Unit test for new classes

## Documentation Plan

* README.md update

## Release Plan

PROMPT (REMOVE-ME): What release work needs to be done to finish this feature? e.g.

* check in PR
* bloom release

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by dabonnie** [comment]
File https://github.com/ros-tooling/system_metrics_collector/pull/46 for package skeleton.

**Comment by thomas-moulard** [comment]
@dabonnie Before jumping into that, could we groom this story and evaluate why rqt is not the right choice?

**Comment by dabonnie** [comment]
SGTM

**Comment by thomas-moulard** [comment]
@ablasdel I think it'd be super helpful to have a quick chat with @dabonnie on this! I think the main challenge using `rqt_plot` is the way the message is organized (all types of data on the same topic with a "name"). Maybe we should have per-metric topic and/or let that being configurable? Does not need to be different message types necessarily.

**Comment by dabonnie** [comment]
> @ablasdel I think it'd be super helpful to have a quick chat with @dabonnie on this! I think the main challenge using `rqt_plot` is the way the message is organized (all types of data on the same topic with a "name"). Maybe we should have per-metric topic and/or let that being configurable? Does not need to be different message types necessarily.

We initially decided to use the same topic name for all the generated metrics because if the topic name is generated dynamically (e.g. for the per process measurements), then this could be problematic for discovery later. For example using an aggregator /  collector (i.e. [cloudwatch metrics](https://github.com/aws-robotics/cloudwatchmetrics-ros2)) would need to ensure it's subscribed to all topics when they appear, otherwise it can sit and listen on a general topic.

**Comment by ablasdel** [comment]
Single topic makes sense I agree. Let’s look into adding “metric message support” to rqt_plot in the new year.

**Comment by dabonnie** [comment]
Bringing out of the icebox :-)

**Comment by emersonknapp** [comment]
closing in favor of a visualizer rqt plugin
