### ISSUE TITLE
ROS 2 nightly performance test

### ISSUE THREAD

**Issue by ahcorde** [ros-tooling/system_metrics_collector#49]
I open this issue to discuss about the current state of the nightly performance test and which are the following steps that we need to focus or discuss

--- 

# Current state

Right now, we have upstream running performance test for each RMW implementation. [Here you can find the plots](http://build.ros2.org/view/Eci/job/Eci__nightly-performance_ubuntu_bionic_amd64/plot/)

 - This [perf_test](https://github.com/ros2/performance_test) is running a publisher and a subscriber in the same process. 

This test can check the performance of each RMW implementation isolated.

### How perf_test stores the data

`perf_test` log the data in a csv file, every second the executable generates a row in this file. When the test has finished we calculate the mean and we create another csv file for jenkins.

### Plots

In Jenkins we can visualize two things:

 - **per-build plots**: These plots are generated with the data outputted by `perf_test` which generates a file like this:

```
---EXPERIMENT-START---
T_experiment,	T_loop,	received,	sent,	lost,	relative_loss,	data_received,	latency_min (ms),	latency_max (ms),	latency_mean (ms),	latency_variance (ms),	pub_loop_res_min (ms),	pub_loop_res_max (ms),	pub_loop_res_mean (ms),	pub_loop_res_variance (ms),	sub_loop_res_min (ms),	sub_loop_res_max (ms),	sub_loop_res_mean (ms),	sub_loop_res_variance (ms),	ru_utime,	ru_stime,	ru_maxrss,	ru_ixrss,	ru_idrss,	ru_isrss,	ru_minflt,	ru_majflt,	ru_nswap,	ru_inblock,	ru_oublock,	ru_msgsnd,	ru_msgrcv,	ru_nsignals,	ru_nvcsw,	ru_nivcsw,	cpu_usage (%),	
1.000822,		1.000821,		909,		909,		2,		0.00,		945540,		0.02721,		5.107,		0.2719,		6.115e-05,		0.8299,		0.9979,		0.9767,		1.358e-07,		-3.27,		0.9984,		0.4494,		0.0002999,		0.2137,		0.1489,		44008,		0,		0,		0,		2129,		0,		0,		0,		16,		0,		0,		0,		5687,		18,		0.0001335,		
2.002013,		1.000767,		905,		905,		0,		0.00,		942158,		0.1896,		1.398,		0.3099,		4.439e-06,		0.899,		0.9919,		0.9705,		2.361e-08,		-1.104,		0.9923,		0.4477,		0.000291,		0.4424,		0.3346,		44008,		0,		0,		0,		2130,		0,		0,		0,		16,		0,		0,		0,		11125,		37,		5.283,		
3.002883,		1.000488,		908,		907,		0,		0.00,		944538,		0.03887,		1.035,		0.2821,		4.685e-06,		0.917,		0.9962,		0.9736,		7.712e-08,		-0.8233,		0.9977,		0.4497,		0.0002883,		0.6583,		0.5007,		44008,		0,		0,		0,		2130,		0,		0,		0,		16,		0,		0,		0,		16572,		49,		4.762,		
```
Example:
![](https://github.com/ros2/buildfarm_perf_tests/raw/master/img/latency.png)

 - **build-over-build jobs**: These plots are generated with the summary of the data from the `perf_test` output.

A example of this file looks like:

```
rmw_cyclonedds_cpp,rmw_cyclonedds_cpp,rmw_cyclonedds_cpp,rmw_cyclonedds_cpp,rmw_cyclonedds_cpp,rmw_cyclonedds_cpp
0.053983333333333335,66100.0,27737.0,27735.0,1.0,0.7297162866666667
```

As may see the first line it just the rmw implementation. This is because the Jenkins plugin use this value to generate the legend. [Here](https://github.com/ros2/ros_buildfarm_config/blob/ros2/eloquent/ci-nightly-performance.yaml#L135) you can find how you can integrate a new plot in Jenkins. The column is selected with [this field](https://github.com/ros2/ros_buildfarm_config/blob/ros2/eloquent/ci-nightly-performance.yaml#L155).

Then the plugin will take care of recording the data for each one of the summarized csv. The plugin will save the data in this [file](https://github.com/ros2/ros_buildfarm_config/blob/ros2/eloquent/ci-nightly-performance.yaml#L159)

![](https://github.com/ros2/buildfarm_perf_tests/blob/master/img/cpu.png?raw=true)

---

# Next steps

In the previous tests we are only considering the performance in term of networking. But thanks to this pkg we will be able to log memory and cpu usage.

### Current implementation

 - In this case we need to split the process in two: publisher and subscriber. `perf_test` allow us to create a Publisher and a Subscriber using different processes and select the rmw implementation for each one.
 - To collect the data I have create a [program](https://github.com/ahcorde/buildfarm_perf_tests/blob/ahcorde/simple_pub_sub_multidds/src/main_measurements.cpp) to "track" the pid of a program based on the name and the arguments. This program collects virtual memory, physical memory, resident anonimous memory and cpu usage. Again we need to have two version one will all the data to create **per-build plots** and other one with the summary for Jenkins.

### Future implementation

Instead of using `perf_test` I think that the idea is to use this pkg which extends the current implementation of a Node and collect the CPU and memory usage of a node. Publishing the data in a topic.

Thing that I think are relevant are:

 - Log the data for each one of the node.
     - [ ] We need a file with all the data to generate the **per-build plots**
     - [ ] We also need a summarize version of the data with the mean, median, percentile 95 or others. To plot this data in Jenkins.
 - Is the node the one who should collects the data? Can this add a overhead to the memory or cpu?

**Comment by dabonnie** [comment]
Hi Alejandro,

> Log the data for each one of the node.

Is there any reason to not use [rosbag2](https://github.com/ros2/rosbag2)? Otherwise, have you considered writing a simple subscriber to receive the [MetricsMessage](https://github.com/ros-tooling/system_metrics_collector/blob/master/metrics_statistics_msgs/msg/MetricsMessage.msg) and log that specific to your needs?

>Is the node the one who should collects the data? Can this add a overhead to the memory or cpu?

Right now we have a PR in flight to add per process CPU measurement. Once this has been merged we can launch the system metrics collector (system cpu + memory) along with the process cpu + memory nodes and determine the total overhead of the system data collection. Does this make sense?

I'm also curious if you would like to see any other system metrics published.

**Comment by dabonnie** [comment]
@ahcorde how would you like to proceed here given some of our offline discussions?

**Comment by ahcorde** [comment]
Hi @dabonnie,

I'm coding a solution with the python subscriber. But I have some doubts about how to use properly this tool.

I have defined in this [issue](https://github.com/ros2/buildfarm_perf_tests/issues/9) the desired tests.

 - **static load test**: For this example I can use the `main` executable  and I will get a node spinning ( not alone with some nodes :( ) and then subscriber to the topic to record all the data.

Here again I raise my point. The objetive of this test it's to evaluate one process spinning for 1 minute to measure ROS 2 overhead and detect obvious leaks. But we are attaching to this single node spinning at least two publisher (process CPU and process Memory) o even 2 more if we also include the system metrics. Adding this overhead with these publishers I think it's impossible to really measure the overhead of this test. Thoughts?

 - **Simple pub/sub**: But for the second test where we have a simple publisher and subscriber in two splited processes. I don't really know how to use your tool. For two reason:
 1) We are using perf_test from Apex.AI and I don't really know how to include your system metrics collector in this tool. I can't launch perf_test as a component so I can't use your components and system metrics collector headers are still hide which means I can't modify the source code too.
 2) Other options it's to create a simple publisher and subscriber and compile it inside the buildfarm_perf_test and use your components to attach the LinuxProcessCpuMeasurementNode and LinuxProcessMemoryMeasurementNode.

should we go with the second solution? I think that using `perf_test` it's convenient because we can check that DDS vendors are compatible between each others. With the proposed solution there is no garanties that the data is there.

**Comment by emersonknapp** [comment]
@ahcorde can we close this issue based on the state of offline discussion?
