### ISSUE TITLE
Follow ROS2 Style Guide

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/system_metrics_collector#50]
## Description

Many constants defined in this project do not follow the guidelines for [ROS2 Development](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#id1). These should be respected.

## Expected Behavior
Constants following style guide naming convention.

## Actual Behavior
Constant naming does not follow the style guide naming convention.

**Comment by dabonnie** [comment]
Opened https://github.com/ros-tooling/system_metrics_collector/pull/51

**Comment by mm318** [comment]
There's more to this than just the names of the constants.

**Comment by thomas-moulard** [comment]
@mm318 Please list the necessary changes to make your comment actionable.

**Comment by mm318** [comment]
The other issues that are immediately noticeable are:
- Function names need to `UpperCamelCase`
- Class member variables need to be suffixed with `_`
These are being addressed in https://github.com/ros-tooling/system_metrics_collector/pull/53.

**Comment by mm318** [comment]
Also found that some class and function comments start with a noun (a subject) or with a singular verb (imperative mood) and do not end with proper punctuation (a period).

Looking at the [examples](https://google.github.io/styleguide/cppguide.html#Class_Comments), it seems like both class and function comments should be in the indicative mood without a subject (the subject is implied to be the class or function that the comment is for) with proper punctuation.

**Comment by dabonnie** [comment]
Closed via https://github.com/ros-tooling/system_metrics_collector/pull/51 and https://github.com/ros-tooling/system_metrics_collector/pull/56
