### ISSUE TITLE
Fix relative #include paths

### ISSUE THREAD

**Issue by mm318** [ros-tooling/system_metrics_collector#60]
Some of the source files have long include paths like:
```
#include "../../src/system_metrics_collector/linux_cpu_measurement_node.hpp"
```
When they're more preferably to be something like:
```
#include "linux_cpu_measurement_node.hpp"
```

For sources under `test`, additional `-I` include directories may be needed. For other sources, no additional `-I` include directories are needed.

**Comment by thomas-moulard** [comment]
By adding `-I` for multiple nested directories, you actually take the risk of having naming conflicts. i.e. if you have `a/foo.hpp` and `b/foo.hpp`, you'll sometimes include one or the other, depending on the `-I` flags order. Instead, what about always adding `<root>/src` ? The include will look better and the risk of conflicts will be limited. We'll also be able to make that "standard" for all our packages (as we'll always have a `src` dir).

**Comment by dabonnie** [comment]
Opened https://github.com/ros-tooling/system_metrics_collector/pull/95

**Comment by emersonknapp** [comment]
@dabonnie, instead of linking this direction, can you please use the

Closes #XX 

syntax on the pull request description? Then closing will happen automatically as well
